# Usa una imagen oficial de Python
FROM python:3.10-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos al contenedor
COPY . /app

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto por donde correrá FastAPI
EXPOSE 8000

# Comando para ejecutar FastAPI
CMD ["uvicorn", "kafka-producer-pg:app", "--host", "0.0.0.0", "--port", "8000"]
